export type Role = 'CUSTOMER' | 'STAFF' | 'MANAGER' | 'ADMIN';
export type { OrderStatus } from '@terrasse-bleue/types';
import type { OrderStatus } from '@terrasse-bleue/types';
export type User = { id: string; name: string; email: string; phone?: string | null; role: Role; createdAt: string };
export type AuthResponse = { user: User; accessToken: string; refreshToken: string };
export type OptionValue = { id: string; label: string; priceDelta: string; sortOrder: number; isActive: boolean };
export type ProductOption = { id: string; name: string; sortOrder: number; isActive: boolean; values: OptionValue[] };
export type Category = { id: string; name: string; description?: string | null; imageUrl?: string | null; isActive: boolean; sortOrder: number; _count?: { products: number } };
export type Product = { id: string; categoryId: string; name: string; description: string; price: string; imageUrl?: string | null; isAvailable: boolean; isFeatured: boolean; category: Category; options: ProductOption[] };
export type OrderItem = { id: string; productNameSnapshot: string; unitPrice: string; quantity: number; subtotal: string; selectedOptions?: unknown };
export type StatusHistory = { id: string; previousStatus?: OrderStatus | null; newStatus: OrderStatus; createdAt: string; changedBy?: { id: string; name: string; role: Role } | null };
export type DeliveryAddress = { recipientName: string; phone: string; addressLine: string; neighborhood?: string; landmark?: string; instructions?: string; city: string };
export type AdminOrder = { id: string; orderNumber: string; status: OrderStatus; orderType: 'DINE_IN' | 'TAKEAWAY' | 'DELIVERY'; subtotal: string; deliveryFee: string; deliveryAddress?: DeliveryAddress | null; total: string; notes?: string | null; createdAt: string; updatedAt: string; user: Omit<User, 'role'>; items: OrderItem[]; payment?: { method: 'CASH' | 'ONLINE'; status: string; amount: string } | null; statusHistory: StatusHistory[] };
export type Page<T> = { items: T[]; meta: { page: number; limit: number; total: number; pages: number } };
export type DashboardData = { date: string; todayOrders: number; counts: Record<OrderStatus, number>; todayRevenue: string; recentOrders: AdminOrder[]; actionOrders: AdminOrder[] };
export type Customer = { id: string; name: string; email: string; phone?: string | null; createdAt: string; orderCount: number; completedOrderCount: number; revenue: string };
export type ReportsData = { period: { today: string; week: string }; ordersToday: number; ordersWeek: number; revenueToday: string; revenueWeek: string; ordersByStatus: { status: OrderStatus; count: number }[]; bestSellingProducts: { name: string; quantity: number; revenue: string }[] };
export type RestaurantSettings = { id: string; restaurantName: string; address: string; contactPhone?: string | null; contactEmail?: string | null; isOpen: boolean; acceptsOrders: boolean; estimatedPrepMinutes: number; notificationSound: boolean; updatedAt: string };
export type StaffMember = Pick<User, 'id' | 'name' | 'email' | 'phone' | 'role' | 'createdAt'>;
