import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { BottomNav } from '@/components/BottomNav';
import { Badge } from '@/components/Badge';
import { Button } from '@/components/Button';
import { useAuthStore } from '@/store/auth-store';
import { colors, radius } from '@/theme/colors';
function ProfileRow({ icon, label, value, onPress }: { icon: keyof typeof Ionicons.glyphMap; label: string; value?: string; onPress?: () => void }) { return <Pressable disabled={!onPress} onPress={onPress} style={styles.row}><View style={styles.rowIcon}><Ionicons name={icon} size={21} color={colors.turquoise} /></View><View style={styles.rowCopy}><Text style={styles.rowLabel}>{label}</Text>{value ? <Text style={styles.rowValue}>{value}</Text> : null}</View>{onPress ? <Ionicons name="chevron-forward" size={20} color={colors.muted} /> : null}</Pressable>; }
export default function ProfileScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const user = useAuthStore((state) => state.user); const logout = useAuthStore((state) => state.logout);
  if (!user) return <View style={styles.page}><View style={[styles.guest, { paddingTop: insets.top + 40 }]}><Ionicons name="person-circle-outline" size={76} color={colors.turquoise} /><Text style={styles.title}>Votre espace client</Text><Text style={styles.notice}>Connectez-vous pour commander et retrouver votre historique.</Text><Button label="Se connecter ou créer un compte" onPress={() => router.push('/auth')} /></View><BottomNav /></View>;
  const initials = user.name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase();
  return <View style={styles.page}><ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 20 }]}><Text style={styles.eyebrow}>MON ESPACE</Text><Text style={styles.title}>Profil</Text><View style={styles.identity}><View style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></View><View style={styles.identityCopy}><Text style={styles.name}>{user.name}</Text><Badge label="Compte client" tone="neutral" /></View></View><View style={styles.card}><ProfileRow icon="mail-outline" label="E-mail" value={user.email} /><ProfileRow icon="call-outline" label="Téléphone" value={user.phone ?? 'Non renseigné'} /><ProfileRow icon="receipt-outline" label="Historique des commandes" onPress={() => router.push('/history')} /></View><Pressable onPress={() => void logout().then(() => router.replace('/'))} style={styles.logout}><Ionicons name="log-out-outline" size={21} color={colors.danger} /><Text style={styles.logoutText}>Se déconnecter</Text></Pressable></ScrollView><BottomNav /></View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.warmIvory }, guest: { flex: 1, padding: 28, justifyContent: 'center', alignItems: 'stretch', gap: 18 }, content: { paddingHorizontal: 18, paddingBottom: 30 }, eyebrow: { color: colors.terracotta, letterSpacing: 1.6, fontSize: 11, fontWeight: '800' }, title: { marginTop: 3, color: colors.primaryBlue, fontSize: 34, fontWeight: '800' }, identity: { marginVertical: 24, flexDirection: 'row', alignItems: 'center', gap: 15 }, avatar: { width: 76, height: 76, borderRadius: 38, backgroundColor: colors.primaryBlue, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.white, fontSize: 24, fontWeight: '800' }, identityCopy: { gap: 7 }, name: { color: colors.primaryBlue, fontSize: 22, fontWeight: '800' }, card: { paddingHorizontal: 16, borderRadius: radius.lg, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border }, row: { minHeight: 72, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, rowIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.paleTurquoise, alignItems: 'center', justifyContent: 'center' }, rowCopy: { flex: 1, marginLeft: 12 }, rowLabel: { color: colors.primaryBlue, fontWeight: '700' }, rowValue: { marginTop: 3, color: colors.muted, fontSize: 13 }, logout: { minHeight: 54, marginTop: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, logoutText: { color: colors.danger, fontWeight: '700' }, notice: { color: colors.muted, fontSize: 14, lineHeight: 21, textAlign: 'center' } });
